### ISSUE TITLE
Alarm state sensor type

### ISSUE THREAD

**Issue by pckeller29** [AndreMiras/edilkamin.py#6]
Hi

I keep having this message in my HA log:

`ValueError: Sensor sensor.celia_alarm_state has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'None' (<class 'str'>)
`

Where celia is my stove name.
I haven't found a suitable device_class for this entity. On the other hand, if I read correctly HA documentation about binary sensors:

> Binary sensors are similar to other sensors in that they monitor the states and conditions of different entities. Where binary sensors differ is they can only return one of two mutually exclusive values. For example, a binary sensor for a window may report a value of open or closed, a switch on or off, a condition true or false.

Shouldn't alarm_state be a binary sensor instead of a normal sensor ?
Thank you

**Comment by pckeller29** [comment]
I reply to myself:
Actually no, it should not be a binary_sensor since alarm_state can have multiple values. Unfortunately, instead of "0" it has the value of "None" which creates my issue.

**Comment by pckeller29** [comment]
I think I solved my issue. I set alarm_state and last_alarm_state device_class as ENUM.
Hope it may help!

**Comment by AndreMiras** [comment]
Thanks for documenting your findings :pray:
